### ISSUE TITLE
requirements could not be resolved

### ISSUE THREAD

**Issue by GMTeams** [do-while/contao-pdf-template#1]
Contao 4.4

Contao Manager says:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Can only install one of: tecnickcom/tcpdf[6.2.17, 6.2.13].
>     - Can only install one of: tecnickcom/tcpdf[6.2.13, 6.2.17].
>     - setasign/fpdi-tcpdf 1.6.2 requires tecnickcom/tcpdf 6.2.13 -> satisfiable by tecnickcom/tcpdf[6.2.13].
>     - do-while/contao-pdf-template-bundle 1.0.0 requires setasign/fpdi-tcpdf 1.6.2 -> satisfiable by setasign/fpdi-tcpdf[1.6.2].
>     - Installation request for do-while/contao-pdf-template-bundle ^1.0 -> satisfiable by do-while/contao-pdf-template-bundle[1.0.0].
>     - Installation request for tecnickcom/tcpdf (locked at 6.2.17) -> satisfiable by tecnickcom/tcpdf[6.2.17].
> 
> <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
> Finished Composer Cloud resolving.

Maybe I have to change configuration? Thanks!

**Comment by do-while** [comment]
The problem was that the version of setasign/fpdi-tcpdf was working with a different version of TCPDF than the current Contao.
For setasign/fpdi-tcpdf there was an update, now it should work.
