### ISSUE TITLE
no settings selectable if root page is declared as language fallback

### ISSUE THREAD

**Issue by DenizGelion** [do-while/contao-pdf-template#3]
As the title suggests, in Contao 4.9.1 I couldn't find any settings in website roots, except when a root page is NOT the fallback page. Took me ages to figure it out. Looks like a bug to me.

**Comment by do-while** [comment]
I have had to search for the reason for a very long time. Starting with contao 4.9 there is a new page type called "rootfallback", which also must get the settings.

The new version 1.3.0 is available
